import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar/NavBar';
import Container from '@/components/Container/Container';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-full`}>
        <header className="p-5 border-b border-accent-blue">
          <Container>
            <NavBar />
          </Container>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="flex items-center justify-center p-10 border-t border-accent-blue">FOOTER</footer>
      </body>
    </html>
  );
}
